[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker run -p 11235:11235 unclecode/crawl4ai:basic"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[ports]]
port = "11235"
protocol = "tcp"